In [1]:
import torch
import numpy as np

In [2]:
!pip list

Package              Version
-------------------- ------------
anyio                3.5.0
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
arrow                1.2.2
asttokens            2.0.5
attrs                21.4.0
Babel                2.10.1
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.0
bokeh                2.4.3
branca               0.5.0
certifi              2021.10.8
cffi                 1.15.0
charset-normalizer   2.0.12
click                8.1.3
colorama             0.4.4
colorcet             3.0.0
cx-Oracle            8.3.0
cycler               0.11.0
debugpy              1.6.0
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
et-xmlfile           1.1.0
executing            0.8.3
fastjsonschema       2.15.3
filelock             3.13.3
folium               0.12.1.post1
fonttools            4.33.3
fsspec               2024.3.1
greenlet             1.1.2
holoviews            1.14.9
idna                 3

## Tensors

<ul>
    <li>A torch.Tensor is a multi-dimentional matrix containing the elements of a single data type</li>
    <li>Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's)</li>
    <li>Default datatype is flaot32</li>
    <li>More suitable for Deep Learning</li>
 </ul>

### Lists

In [3]:
my_list = [[1,2,3,4,5],[22,34,56,78,12]]
my_list

[[1, 2, 3, 4, 5], [22, 34, 56, 78, 12]]

### Numpy Arrays

In [4]:
np1 = np.random.rand(3,4)

In [5]:
np1

array([[0.49183756, 0.68812339, 0.62154985, 0.61656703],
       [0.61873115, 0.60672105, 0.82994383, 0.19961875],
       [0.01663999, 0.31460234, 0.37290144, 0.64221149]])

In [6]:
np1.dtype

dtype('float64')

### Tensors

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.0596,  0.7704, -1.0503,  0.5291],
        [ 0.1136, -0.4254,  0.0331,  1.1924],
        [-0.7842,  0.2248,  0.1476, -0.6204]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## create tensor out of numpy
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4918, 0.6881, 0.6215, 0.6166],
        [0.6187, 0.6067, 0.8299, 0.1996],
        [0.0166, 0.3146, 0.3729, 0.6422]], dtype=torch.float64)

#### Another way to make tensor out of numpy array

In [10]:
data = [[1, 2],[3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

### Directly from data

In [11]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

### Attributes of tensor

In [12]:
tensor = torch.rand(3,4)

In [13]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensoris stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensoris stored on: cpu


In [14]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


### Tensor to Numpy

In [15]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


#### A change in the tensor reflects in the NumPy array.

In [16]:
t.add_(6)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([7., 7., 7., 7., 7.])
n: [7. 7. 7. 7. 7.]


### Standard numpy-like indexing and slicing:

In [17]:
tensor = torch.ones(4,4)
print(f"First Row: {tensor[0]}")
print(f"First Column: {tensor[:,0]}")
print(f"First Column: {tensor[:,-1]}")
tensor[:,1]=0
print(tensor)

First Row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


<h3>Joining tensors</h3>
<p>You can use <b><i>torch.cat</i></b> to concatenate a sequence of tensors along a given dimension.</p>

In [18]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#### torch.stack

In [19]:
t1 = torch.stack([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


### Arithmetic operations

#### Matrix Multiplication

In [20]:
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [21]:
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [22]:
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

#### Element-wise multiplication

In [23]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

#### Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [25]:
agg = tensor.sum()
agg

tensor(12.)

In [26]:
agg_item = agg.item()
agg_item

12.0

#### In-place operations: Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [27]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [28]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### RESHAPE

In [29]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
#### Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(20)
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

### VIEW (Similar to  Reshape)

In [31]:
my_torch3 = torch.arange(20)
my_torch3 = my_torch3.reshape(2,-1)
my_torch3

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

#### Assignment Operator

In [32]:
my_torch3[0][1] = 9191
my_torch3

tensor([[   0, 9191,    2,    3,    4,    5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19]])

#### Slicing

In [33]:
my_torch3[1:4]

tensor([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [34]:
my_torch3 = my_torch3.reshape(-1,2)
my_torch3

tensor([[   0, 9191],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9],
        [  10,   11],
        [  12,   13],
        [  14,   15],
        [  16,   17],
        [  18,   19]])

In [35]:
my_torch3[:,1]

tensor([9191,    3,    5,    7,    9,   11,   13,   15,   17,   19])

In [36]:
# Return column
my_torch3[:,1:]

tensor([[9191],
        [   3],
        [   5],
        [   7],
        [   9],
        [  11],
        [  13],
        [  15],
        [  17],
        [  19]])

### Tensor addition

In [39]:
tensor_a = torch.tensor([1,4,3,2])
tensor_b = torch.tensor([3,2,5,8])
tensor_a+tensor_b

tensor([ 4,  6,  8, 10])

In [40]:
torch.add(tensor_a,tensor_b)

tensor([ 4,  6,  8, 10])

### Tensor Substraction

In [41]:
tensor_a-tensor_b

tensor([-2,  2, -2, -6])

In [42]:
torch.sub(tensor_a,tensor_b)

tensor([-2,  2, -2, -6])

### Tensor Multiplication(Its not matrix multiplication or dot product)

In [44]:
tensor_a*tensor_b

tensor([ 3,  8, 15, 16])

In [45]:
torch.mul(tensor_a,tensor_b)

tensor([ 3,  8, 15, 16])

### Tensor Division

In [46]:
tensor_a / tensor_b

tensor([0.3333, 2.0000, 0.6000, 0.2500])

In [47]:
torch.div(tensor_a,tensor_b)

tensor([0.3333, 2.0000, 0.6000, 0.2500])

### Tensor Modulus(Remainder)

In [49]:
tensor_a % tensor_b

tensor([1, 0, 3, 2])

In [51]:
torch.remainder(tensor_a,tensor_b)

tensor([1, 0, 3, 2])

### Tensor Exponents/Power

In [53]:
torch.pow(tensor_a,tensor_b)

tensor([  1,  16, 243, 256])