#### Objectives
1. Build Dataset Class
2. Build Dataset Transform
3. Compose Transforms

In [1]:
import torch
from torch.utils.data import Dataset

In [2]:
class toy_set(Dataset): #toy_set is subclass of Dataset class
    
    def __init__(self,length=100,transform=None):
        
        self.x = 2*torch.ones(length,2) #independent variable
        self.y = torch.ones(length,1) #dependent variable
        self.len = length #no. of samples
        self.transform = transform
        
    def __getitem__(self,index):
        sample = self.x[index], self.y[index] # tensor([2,2]) , Tensor([1,1])
        
        if self.transform:
            sample = self.transform(sample)
        
        return sample
    
    def __len__(self):
        self.len
        

1. self.x ---> [2,2]
2. self.y ---> [1,1]
3. index ----> 0,1,2....98,99
4. The dataset object behaves like a list or tuple or any python iterable --> dataset[index]
5. __getitem__() is a magic method in Python, which when used in a class, allows its instances to use the [] (indexer) operators. Say x is an instance of this class, then x[i] is roughly equivalent to type(x).__getitem__(x, i).

In [3]:
dataset = toy_set()

In [4]:
for i in range(3):
    x,y = dataset[i]
    print(f'{i})  x:{x}  y:{y}')

0)  x:tensor([2., 2.])  y:tensor([1.])
1)  x:tensor([2., 2.])  y:tensor([1.])
2)  x:tensor([2., 2.])  y:tensor([1.])


In [5]:
dataset.__getitem__(1)

(tensor([2., 2.]), tensor([1.]))

In [6]:
dataset[1]

(tensor([2., 2.]), tensor([1.]))

#### Transforms
1. In many cases we would like to transform the data
2. For example normalize or standardize the data
3. Instead of writing a function, we will create callable classes
4. The objects we create from these classes will apply transforms  to the tensors

In [7]:
class add_mult(object):
    def __init__(self, addx=1, muly=1):
        self.addx = addx
        self.muly = muly
        
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        
        sample = x,y
        return sample

In [8]:
#### __call__()
# Python has a set of built-in methods and __call__ is one of them. 
#The __call__ method enables Python programmers to write classes where the instances behave like functions 
#and can be called like a function. When the instance is called as a function; 
#if this method is defined, x(arg1, arg2, ...) is a shorthand for x.__call__(arg1, arg2, ...).

In [9]:
a_m = add_mult()
x_, y_ = a_m(dataset[0])

In [10]:
x_, y_

(tensor([3., 3.]), tensor([1.]))

In [11]:
a_m = add_mult()
dataset_ = toy_set(transform=a_m)

In [12]:
dataset_[0]

(tensor([3., 3.]), tensor([1.]))

#### Transforms Compose

In [13]:
class mult(object):
    def __init__(self, mul=100):
        self.mul=mul
        
    def __call__(self,sample):
        x = sample[0]
        y = sample[1]
        
        x = x*self.mul
        y = y*self.mul
        
        sample = x,y
        return sample

### Torchvision is mainly used for images

In [14]:
from torchvision import transforms

In [15]:
data_transform = transforms.Compose([add_mult(), mult()])

In [16]:
x_, y_ = data_transform(dataset[0])

In [17]:
#### Operation flow
# dataset[0] -----> add_mult() ----> mult() ---> Output(x_, y_)

In [18]:
x_, y_

(tensor([300., 300.]), tensor([100.]))